front_end:
    resource: "@FrontEndBundle/Resources/config/routing.yml"
    prefix:   /

back_office:
    resource: "@BackOfficeBundle/Resources/config/routing.yml"
    prefix:   /backoffice

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
