# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        BackOfficeBundle\Entity\User:
            algorithm: bcrypt

    providers:
        dbal:
            entity:
                class: BackOfficeBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/backoffice/login$
            anonymous: true

        secured_area:
            pattern:    ^/backoffice
            provider:   dbal
            form_login:
                login_path:  /backoffice/login
                check_path:  /backoffice/login_check
            logout:
                path:   /backoffice/logout
                target: /

    access_control:
        - { path: ^/backoffice/(login|login_check)$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backoffice, roles: ROLE_USER }
