login:
    path: /login
    defaults: { _controller: BackOfficeBundle:Security:login }

login_check:
    path: /login_check

logout:
    pattern: /logout

back_office_homepage:
    path:     /
    defaults: { _controller: BackOfficeBundle:Default:index }

back_office_invoice_list:
    path:     /invoice/list
    defaults: { _controller: BackOfficeBundle:Default:invoiceList }

back_office_invoice_view:
    path:     /invoice/view/{invoiceId}
    defaults: { _controller: BackOfficeBundle:Default:invoiceView }

back_office_invoice_change_status:
    path:     /invoice/change-status/{invoiceId}
    defaults: { _controller: BackOfficeBundle:Default:invoiceChangeStatus }

back_office_simulate_sending_date:
    path:     /utils/simulate-sending-date
    defaults: { _controller: BackOfficeBundle:Default:simulateSendingDate }
